/********************************************************************
* src/MonTaskDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/MonTaskDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMonTaskDict();
extern void G__cpp_setup_inheritanceMonTaskDict();
extern void G__cpp_setup_typetableMonTaskDict();
extern void G__cpp_setup_memvarMonTaskDict();
extern void G__cpp_setup_globalMonTaskDict();
extern void G__cpp_setup_memfuncMonTaskDict();
extern void G__cpp_setup_funcMonTaskDict();
extern void G__set_cpp_environmentMonTaskDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MonTask.h"
#include "MonBenchDist.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MonTaskDictLN_TClass;
extern G__linked_taginfo G__MonTaskDictLN_TBuffer;
extern G__linked_taginfo G__MonTaskDictLN_TMemberInspector;
extern G__linked_taginfo G__MonTaskDictLN_string;
extern G__linked_taginfo G__MonTaskDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MonTaskDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MonTaskDictLN_TTimer;
extern G__linked_taginfo G__MonTaskDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MonTaskDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MonTaskDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__MonTaskDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__MonTaskDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MonTaskDictLN_TCanvas;
extern G__linked_taginfo G__MonTaskDictLN_TH1F;
extern G__linked_taginfo G__MonTaskDictLN_MonTask;
extern G__linked_taginfo G__MonTaskDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__MonTaskDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MonTaskDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MonTaskDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MonTaskDictLN_MonBenchDist;

/* STUB derived class for protected member access */
